version: '3'

services:

  driveweavedb:
    container_name: driveweavedb
    image: mongo:4.4.25-focal
    ports:
      - 27017:27017
    volumes:
      - ./db/:/usr/data/db

  driveweaveserver:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: driveweaveserver
    env_file:
      - .env
    environment:
      - DB_URL=mongodb://driveweavedb:27017/driveweave
      - PORT=5000
    ports:
      - 5000:5000
    depends_on:
      - driveweavedb
    restart: always
    volumes:
      - ./:/usr/driveweaveserver
    